#~/.config/starship.toml

scan_timeout = 500
command_timeout = 5000

format = """
[░▒▓](#a3aed2)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
$all\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)
\n$character
"""

[[battery.display]]
threshold = 100

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
format = ' $time'